### PR TITLE
Corrected and Improved Items display in Log

### PR DESCRIPTION
**Pull request by fabien-gigante**
1) Transform typical json strings into user friendly text
2) Check for item words by descending length (because 'Super Potion' contains 'Potion', the icon was showing twice)
3) Parse quantities and display count next to icon
4) Specific icons for specific actions

### CODE REVIEW

**Comment by Outpox** [comment]
Hey! Thanks for your time, unfortunatly we've been reworking the whole app for some times now in the `vuejs-rework-gulp` [branch](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/tree/vuejs-rework-gulp).

**Comment by roshcamlian** [comment]
@Outpox y u no make minor updates :(

**Comment by Outpox** [comment]
'Cause we remade the build process and changed the tools used. It will allow us to work much faster once it's done.

**Comment by roshcamlian** [comment]
@Outpox Wish you all the best to get it done soon and polished! I am so thankful! :heart_eyes:

**Comment by fabien-gigante** [comment]
OK, I understand. If you are interested by the change, tell me whenever you are ready with the reworking activity, and I can port it wherever you want it to be.

**Comment by Outpox** [comment]
Yep, that's why I didn't close the PR in the first time :P

**Comment by roshcamlian** [comment]
yo @Outpox how's it going?

**Pull request closed without merging**
